apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: argocd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"username\":\"_\",\"password\":\"%s\"}}}" .Values.ghcrToken | b64enc }}
