apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
  annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: longhorn-system
    server: {{.Values.spec.destination.server}}
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.6.0 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          helmPreUpgradeCheckerJob:
            enabled: false
